server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: tempuser
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
    ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /customer-documentation
    tryItOutEnabled: true
  api-docs:
    path: /customer-api-docs
  packages-to-scan: com.sogeti.customerservice