server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: lease-service
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: test
    password: temptest
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: user

carservice:
  url: http://mbp-van-mac.home:8060/cars

customerservice:
  url: http://mbp-van-mac.home:8060/customers

springdoc:
  swagger-ui:
    path: /lease-documentation
    tryItOutEnabled: true
  api-docs:
    path: /lease-api-docs
  packages-to-scan: com.sogeti.leaseservice