server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers/(?<path>.*), /$\{path}
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**
          filters:
            - RewritePath=/cars/(?<path>.*), /$\{path}
        - id: lease-service
          uri: lb://lease-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: car
        url: /v3/api-docs/car
      - name: customer
        url: /v3/api-docs/customer
      - name: lease
        url: /v3/api-docs/lease

management:
  tracing:
    sampling:
      probability: 1.0
