server:
  port: 8060
spring:
  application:
    name: gateway-service
  output:
    ansi:
      enabled: always
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://mbp-van-mac.home:8091/customers
          predicates:
            - Path=/customers/**, /openapi/**, /customer-api-docs/**
        - id: cars-service
          uri: http://mbp-van-mac.home:8092/cars
          predicates:
            - Path=/cars/**
        - id: lease-service
          uri: http://mbp-van-mac.home:8093/api
          predicates:
            - Path=/api/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

springdoc:
  swagger-ui:
    urls:
      - name: customers
        url: http://mbp-van-mac.home:8091/customer-api-docs
      - name: cars
        url: http://mbp-van-mac.home:8092/car-api-docs
      - name: leasecars
        url: http://mbp-van-mac.home:8093/lease-api-docs