server:
  port: 8761
spring:
  application:
    name: discovery-service
  output:
    ansi:
      enabled: always
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  tracing:
    sampling:
      probability: 1.0